pipeline {
    agent { node { label 'jenkins-workers' } }

    options {
        buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10'))
    }

    triggers {
        pollSCM('@weekly')
    }

    stages {

        stage('Build') {
            steps {
                sh '''#!/bin/bash -ex

DISTROS=("jessie" "stretch" "buster")
ARCHS=("amd64")
for distro in ${DISTROS[@]}
do
    for arch in ${ARCHS[@]}
    do
        VERSION=$(date +"%Y%m%d%H%M%S")
        TARGET_NAME="image-host-${arch}-${distro}_$(VERSION)"
        sudo debootstrap --variant=minbase --arch "$arch"  "$distro" "$TARGET_NAME" http://debian-archive.trafficmanager.net/debian
        pushd "${TARGET_NAME}"
        sudo tar -zvcf "${WORKSPACE}/${TARGET_NAME}.tar.gz" .
        popd
    done
done
'''
            }
        }
    }
    post {
        success {
            azureUpload allowAnonymousAccess: true, blobProperties: [cacheControl: '', contentEncoding: '', contentLanguage: '', contentType: '', detectContentType: true], containerName: 'packages', fileShareName: '', filesPath: '*.gz', storageCredentialId: 'sonicstoragepublic', storageType: 'blobstorage', uploadArtifactsOnlyIfSuccessful: true
        }
        cleanup {
            cleanWs(disableDeferredWipeout: false, deleteDirs: true, notFailBuild: true)
        }
    }
}
